mythril.interfaces.cli [ERROR]: Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 845, in parse_args_and_execute
    disassembler=disassembler, address=address, parser=parser, args=args
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 757, in execute_command
    transaction_count=args.transaction_count,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/mythril/mythril_analyzer.py", line 180, in fire_lasers
    issue.add_code_info(contract)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/analysis/report.py", line 145, in add_code_info
    self.address, constructor=(self.function == "constructor")
  File "/home/ubuntu/.local/lib/python3.6/site-packages/mythril/solidity/soliditycontract.py", line 195, in get_source_info
    solidity_file = self.solc_indices[mappings[index].solidity_file_idx]
KeyError: -1
 

---------------------------------------------
For contract 0x642bF34F2aeC4c28a8273C8f032c1b0a21EceDcf.sol
Tool Runtime = 156.26117481899564 seconds
#############################################