mythril.mythril [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/home/ubuntu/Mpro/M-Pro/mythril/mythril.py", line 629, in slither_mythril
    heuristic=priority
  File "/home/ubuntu/Mpro/M-Pro/mythril/analysis/symbolic.py", line 103, in __init__
    creation_code=contract.creation_code, contract_name=contract.name, heuristic=heuristic, disassembly = contract.disassembly
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/svm.py", line 149, in sym_exec
    self, creation_code, contract_name
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/transaction/symbolic.py", line 187, in execute_contract_creation
    laser_evm.exec(True)
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/svm.py", line 254, in exec
    new_states, op_code = self.execute_state(global_state, disassembly, priority=priotity)
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/svm.py", line 303, in execute_state
    global_state
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/instructions.py", line 202, in evaluate
    result = instruction_mutator(global_state)
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/instructions.py", line 146, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/instructions.py", line 90, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/instructions.py", line 1224, in mstore_
    state.memory.write_word_at(mstart, value)
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/state/memory.py", line 82, in write_word_at
    self[index : index + 32] = _bytes
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/state/memory.py", line 135, in __setitem__
    self[start + i] = value[i]
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/state/memory.py", line 142, in __setitem__
    self._memory[key] = value
IndexError: cannot fit 'int' into an index-sized integer
 
mythril.mythril [CRITICAL]: Exception occurred, aborting analysis. Please report this issue to the Mythril GitHub page.
Traceback (most recent call last):
  File "/home/ubuntu/Mpro/M-Pro/mythril/mythril.py", line 629, in slither_mythril
    heuristic=priority
  File "/home/ubuntu/Mpro/M-Pro/mythril/analysis/symbolic.py", line 103, in __init__
    creation_code=contract.creation_code, contract_name=contract.name, heuristic=heuristic, disassembly = contract.disassembly
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/svm.py", line 162, in sym_exec
    self._execute_transactions(created_account.address, heuristic, disassembly)
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/svm.py", line 205, in _execute_transactions
    heuristic_message_call(self, address, heuristic, self.transaction_count, disassembly)
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/transaction/symbolic.py", line 30, in heuristic_message_call
    execute_message_call(laser_evm, callee_address, disassembly)
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/transaction/symbolic.py", line 143, in execute_message_call
    laser_evm.exec(disassembly)
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/svm.py", line 254, in exec
    new_states, op_code = self.execute_state(global_state, disassembly, priority=priotity)
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/svm.py", line 303, in execute_state
    global_state
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/instructions.py", line 202, in evaluate
    result = instruction_mutator(global_state)
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/instructions.py", line 146, in wrapper
    new_global_states = self.call_on_state_copy(func, func_obj, global_state)
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/instructions.py", line 90, in call_on_state_copy
    return func(func_obj, global_state_copy)
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/ethereum/instructions.py", line 401, in add_
    + helper.pop_bitvec(global_state.mstate)
  File "/home/ubuntu/Mpro/M-Pro/mythril/laser/smt/bitvec.py", line 61, in __add__
    union = self.annotations + other.annotations
MemoryError
 
total states: 24
total states: 30

---------------------------------------------
For contract 0x511a878bd440f15c0f6c86590a9a6f3c58d9284b.sol
Tool Runtime = 508.7622521459998 seconds
#############################################